#!/bin/bash

INPUTBOX=${INPUTBOX=dialog}
TITLE="Default"
MESSAGE="Something to say"
XCORD=10
YCord=20

#15 is xcord
#45 is ycord
#4 is the no of choices

function  displayinputbox ()
{
	$INPUTBOX --title "$1" --inputbox "$2" "$3" "$4" 2>tmpfile.txt
}

displayinputbox "Display file name" "Which file is in the current dir?" "10" "20"

if [[ "`cat tmpfile.txt`" != "" ]]; then 
	cat "`cat tmpfile.txt`"
else
	echo "noting"
fi


